### PR TITLE
Fix error case in node connection procedure.

### PR DESCRIPTION
**Pull request by qnikst**
In case if new connection to remote EndPoint failed to create,
this means that all reliable connections (that are used in d-p)
also failed. As a result this means that we need to emit
`Died (node) Disconnect` event. Previously we emited
`Died typeOfReceiver Disconnect` event.

### CODE REVIEW

**Comment by facundominguez** [comment]
I thought this reasoning applied only when the transport yields `EventConnectionLost`. Isn't this event delivered eventually?

I'm wondering if there is a situation where `send` fails but `EventConnectionLost` is not mandated.

**Comment by facundominguez** [comment]
The bug:

    A process PA in NA monitors a process PB in NB
    NA and NB are disconnected
    PA tries to send a message to another process PB1 in NB
    A monitor notification about PB1 death arrives to PA
    No monitor notification about PB arrives to PA.

This is observed only in tests so far. Seems there is a test which motivated this change, which breaks connections with `testBreakConnection`, which doesn't deliver `EventConnectionLost`. If the transport delivered `EventConnectionLost`, then d-p would notify the death of all processes, I hope.

**Comment by facundominguez** [comment]
I'd say we should fix testBreakConnection. I wouldn't mind merging this temporarily. @mboes?

**Comment by mboes** [comment]
I'm lacking context here: why is this patch targeting tweag/distributed-process, rather than haskell-distributed/distributed-process? If this fix has already been merged upstream, can't we just import the upstream patch?

I'd like for us to review our tweag-patchset and minimize it as much as possible.

**Comment by qnikst** [comment]
This is a cherry-pick of upstream patch. I'd like to use upstream d-p as is, but it's have some troubles with our project that worth debugging, but as a separate task.

**Comment by facundominguez** [comment]
This is the PR merged upstream
https://github.com/haskell-distributed/distributed-process/pull/246

The tests in question are MonitorNode, MonitorLiveNode, MonitorChannel from CH. And now in halon the unmerged RS tests are affected too.

Given that this is merged upstream, I'm fine leaving it here and opening an issue to solve some time in the future if ever.

**Pull request merged**
