### PR TITLE
Registry

### PR DESCRIPTION
**Pull request by qnikst**
The main point of this PR is a review, before it will be proposed upstream.

The most interesting part is f878138 where process monitoring were implemented

### CODE REVIEW

**Comment by facundominguez** [comment]
Tests missing.

**Comment by facundominguez** [comment]
Some tests:
* can send messages to remote process in local registry
* can send messages to remote process in remote registry
* when a remote process registered with more than one label dies, the process is unregistered for all its labels
* when a remote process is unregistered from a label, it still can receive messages sent to other labels for which it is registered.
* when a remote process is reregistered, the old remote process dying does not cause the new process to be unregistered.

**Comment by qnikst** [comment]
I'm going to split this PR into 2, one for DP-100 exclusively, and another for nsend.

so in DP-100 tests will be:
  (1) when a local process is registered and died: whereis return Nothing
  (2) when remote process is registered and died: whereis eventually returns Nothing
  (3) - (1) for remote registry
  (4) - (2) for remote registry
  (5) when process is registered twice and unregistrered: whereis for any of it's label returns Nothing
  (6) when process is reregistered: new registry entry will not be removed even if first process died

**Comment by qnikst** [comment]
Tests for DP-100: https://github.com/haskell-distributed/distributed-process-tests/pull/14

**Comment by qnikst** [comment]
If resulting code is fine I can prepare PR for DP-100 only

**Comment by mboes** [comment]
@qnikst close?

**Pull request closed without merging**
